name: chefaa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.2.0
  flutter_bloc: ^8.1.1
  conditional_builder_null_safety: ^0.0.6
  shared_preferences: ^2.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  flutter_launcher_icons: ^0.12.0
  flutter_svg: ^2.0.2
  font_awesome_flutter: ^10.2.1
  carousel_slider: ^4.1.1
  percent_indicator: ^4.2.2
  smooth_star_rating_null_safety: ^1.0.4+2
  image_picker: ^0.8.6
  fl_chart: ^0.61.0
  flutter_datetime_picker: ^1.5.1
  easy_localization: ^3.0.1
  faker: ^2.0.0
  provider: ^6.0.4
  dio:
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  flutter_secure_storage: ^8.0.0
  mime: ^1.0.4
  dartz: ^0.10.1
  geolocator: ^9.0.2
  google_maps_flutter: 
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  awesome_notifications: ^0.6.19
  hive: ^2.2.3
  http: ^0.13.5
  map_launcher: ^2.5.0+1
  url_launcher: ^6.1.10
  flutter_rating_bar: ^4.0.1
  socket_io_client: ^2.0.0-beta.2
  hive_flutter: ^1.1.0
  photo_view: ^0.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.18
flutter_native_splash:
  background_image: "assets/images/splash.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/3.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/fonts/
    - assets/svg/
    - assets/translations/
    - assets/json/

  fonts:
    - family: Madina
      fonts:
        - asset: assets/fonts/madina.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
